### PR TITLE
Fix for password issue closes #27

### LINKED ISSUE #27: Issue with password
Steps to reproduce:

1. Create user with `before&after` password;
2. Try to login with this password;
3. Only `before` string will be sent to the server.

### PR DESCRIPTION
**Pull request by kuisis**

### CODE REVIEW

File: src/components/Signin.js [hunk 1]
```diff
@@ -44,15 +44,15 @@ export default class Signin extends Component {
...
+          body: `username=${encodeURIComponent(this.state.usernameValue.replace(/\s/g, ''))}&password=${encodeURIComponent(this.state.passwordValue)}`
         };
 
     parsed.response_type ? responseType=`response_type=${parsed.response_type}` : responseType="";
     parsed.client_id ? clientId=`&client_id=${parsed.client_id}` : clientId="";
     parsed.state ? state=`&state=${parsed.state}` : state="";
     parsed.redirect_uri ? redirectUri=`&redirect_uri=${encodeURIComponent(parsed.redirect_uri)}` : redirectUri="";
 
-    fetch(`${process.env.REACT_APP_OAUTH_URL}/signin`, options)
+    fetch(`localhost/signin`, options)
```
Comment (wildsurfer) [inline src/components/Signin.js]: This seems to be a problem :)
